=== Blockitifluy/Cyro-Hazard/Data/Items/Items.dtd
<!ELEMENT root (Item+)>
<!ELEMENT Item (type, name, description, health, spoilageRate, decayRate, flamiblity, volitile, recipe, maxStack, sizeX, sizeY, weight)>
<!ATTLIST Item ID ID #REQUIRED>
<!ELEMENT type (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT health (#PCDATA)>
<!ELEMENT spoilageRate (#PCDATA)>
<!ELEMENT decayRate (#PCDATA)>
<!ELEMENT flamiblity (#PCDATA)>
<!ELEMENT volitile (#PCDATA)>
<!ELEMENT recipe (ritem*)>
<!ELEMENT maxStack (#PCDATA)>
<!ELEMENT sizeX (#PCDATA)>
<!ELEMENT sizeY (#PCDATA)>
<!ELEMENT weight (#PCDATA)>

<!ELEMENT ritem (#PCDATA)>
<!ATTLIST ritem ID CDATA #REQUIRED amount CDATA #REQUIRED>

=== Blockitifluy/Cyro-Hazard/Assets/StreamingAssets/Data/Items/Items.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE root SYSTEM "Items.dtd">
<root>
	<Item ID="test-item-2">
		<type>none</type>
    <name>Test Item 2</name>
	  <description>Lorem Ipsum</description>
	  <health>100</health>
	  <spoilageRate>2</spoilageRate>
	  <decayRate>5</decayRate>
	  <flamiblity>1</flamiblity>
	  <volitile>False</volitile>
	  <recipe>
	  	<ritem ID="wood" amount="5"/>
	  </recipe>
		<maxStack>16</maxStack>
	  <sizeX>2</sizeX>
	  <sizeY>2</sizeY>
		<weight>0.05</weight>
  </Item>

  <Item ID="test-item">
		<type>none</type>
    <name>Test Item</name>
	  <description>Lorem Ipsum</description>
	  <health>100</health>
	  <spoilageRate>2</spoilageRate>
	  <decayRate>5</decayRate>
	  <flamiblity>1</flamiblity>
	  <volitile>False</volitile>
	  <recipe>
	  	<ritem ID="wood" amount="5"/>
	  </recipe>
		<maxStack>1</maxStack>
	  <sizeX>2</sizeX>
	  <sizeY>1</sizeY>
		<weight>0.25</weight>
  </Item>
</root>
